---
- hosts: all
  vars_files:
    - ./vars.yml

  tasks:
  - name: Uninstall Katello Agent
    yum:
      state: absent
      name: katello-agent

  - name: Unregister from Satellite 6
    redhat_subscription:
      state: absent
    ignore_errors: True

  - name: Check for existing katello-ca-consumer package, remove it when exist
    package: 
      name: katello-ca-consumer*
      state: absent

  - name: Check if /etc/yum/pluginconf.d/rhnplugin.conf exists
    stat:
      path: /etc/yum/pluginconf.d/rhnplugin.conf
    register: stat_result

  - name: Enable RHN yum Plugin if rhnplugin.conf exists
    lineinfile:
      path: /etc/yum/pluginconf.d/rhnplugin.conf
      regexp: '^enabled'
      line: 'enabled=1'
    when: stat_result.stat.exists == True

  - name: Check Sat5 systemid backup file)
    stat:
      path: /etc/sysconfig/rhn/systemid.backup
    register: stat_result

  - name: Restore /etc/sysconfig/rhn/systemid
    copy: 
      remote_src=True 
      src=/etc/sysconfig/rhn/systemid.backup
      dest=/etc/sysconfig/rhn/systemid
    when: stat_result.stat.exists == True

  - name: Disable RHSM plugin
    lineinfile:
      path: /etc/yum/pluginconf.d/subscription-manager.conf
      regexp: '^enabled'
      line: 'enabled=0'
    when: stat_result.stat.exists == True

  - name: Remove obsolete Yum Cache Directory
    file:
      path: /var/cache/yum
      state: absent

