---
- hosts: all
  vars_files:
    - ./vars.yml

  tasks:
  - name: Check Sat5 systemid backup file)
    stat:
      path: /etc/sysconfig/rhn/systemid.backup
    register: stat_result

  - name: Check if system is subscribed to Sat6 or CDN
    shell: subscription-manager status
    register: subs
    #ignore_errors: True
    changed_when: subs.rc == 2000
    failed_when: subs.rc == 2000

  - name: Unregister from Satellite 6
    redhat_subscription:
      state: absent
    when: stat_result.stat.exists == False or subs.rc == 0

  - name: Check for existing katello-ca-consumer package, remove it when exist
    package: 
      name: katello-ca-consumer*
      state: absent

  - name: Check if /etc/yum/pluginconf.d/rhnplugin.conf exists
    stat:
      path: /etc/yum/pluginconf.d/rhnplugin.conf
    register: stat_result

  - name: Enable RHN yum Plugin if rhnplugin.conf exists
    lineinfile:
      path: /etc/yum/pluginconf.d/rhnplugin.conf
      regexp: '^enabled'
      line: 'enabled=1'
    when: stat_result.stat.exists == True

  - name: Restore /etc/sysconfig/rhn/systemid
    copy: 
      remote_src=True 
      src=/etc/sysconfig/rhn/systemid.backup
      dest=/etc/sysconfig/rhn/systemid
    when: stat_result.stat.exists == True

#  - name: remove proxy entry from /etc/yum.conf
#    lineinfile:
#      path: /etc/yum.conf
#      state: absent
#      regexp: '^proxy=http://{{ proxy_host }}:{{ proxy_port }}'
#      tags:
#        - proxy

#  - name: Remove proxy host entry from /etc/rhsm/rhsm.conf
#    lineinfile:
#      path: /etc/rhsm/rhsm.conf
#      state: absent
#      regexp: '^proxy_hostname={ proxy_host }'
#      tags:
#        - proxy

#  - name: Remove proxy port entry from /etc/rhsm/rhsm.conf
#    lineinfile:
#      path: /etc/rhsm/rhsm.conf
#      state: absent
#      regexp: '^proxy_port={ proxy_port }'
#      tags:
#        - proxy

  - name: Cleanup Yum cache
    shell: yum clean all
    args:
      warn: no

  - name: Remove obsolete Yum Cache Directory
    file:
      path: /var/cache/yum
      state: absent

  - name: Uninstall Katello Agent
    yum:
      state: absent
      name: katello-agent
